---
- hosts: docker
  # tag each role so we can run them individually and our program can find them.
  roles:
    - { role: vuln-ssh, tags: ['vuln-ssh'] }
    - { role: vuln-ftp, tags: ['vuln-ftp'] }
    - { role: vuln-irc, tags: ['vuln-irc'] }

